"""Initial migration with AttendanceSession and updated Attendance models

Revision ID: 74af339e801b
Revises: 
Create Date: 2025-11-09 09:22:37.650496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74af339e801b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('division', sa.String(length=50), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attendance_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_code', sa.String(length=20), nullable=False),
    sa.Column('otp', sa.String(length=10), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('faculty_latitude', sa.Float(), nullable=True),
    sa.Column('faculty_longitude', sa.Float(), nullable=True),
    sa.Column('faculty_location_accuracy', sa.Float(), nullable=True),
    sa.Column('faculty_location_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_division', sa.String(length=50), nullable=True),
    sa.Column('expected_location_radius', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('otp'),
    sa.UniqueConstraint('session_code')
    )
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.create_index('idx_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_faculty_status', ['faculty_id', 'status'], unique=False)
        batch_op.create_index('idx_otp', ['otp'], unique=False)
        batch_op.create_index('idx_session_code', ['session_code'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('student_latitude', sa.Float(), nullable=True),
    sa.Column('student_longitude', sa.Float(), nullable=True),
    sa.Column('student_location_accuracy', sa.Float(), nullable=True),
    sa.Column('distance_from_faculty', sa.Float(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_session.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    with op.batch_alter_table('attendance_session', schema=None) as batch_op:
        batch_op.drop_index('idx_session_code')
        batch_op.drop_index('idx_otp')
        batch_op.drop_index('idx_faculty_status')
        batch_op.drop_index('idx_expires_at')

    op.drop_table('attendance_session')
    op.drop_table('student')
    op.drop_table('faculty')
    # ### end Alembic commands ###
